import shield01a from "../../app/_assets/item/shield01a.png";
import shield01b from "../../app/_assets/item/shield01b.png";

export const ShieldItems = [
    {
      item_id: 10001,
      type: "shield",
      rarity: 'common',
      name: "Навчальний щит",
      description: "",
      damage: 0,
      defense: 8,
      price: 65,
      image: shield01a.src,
    },
    {
      item_id: 100012,
      type: "shield",
      rarity: 'uncommon',
      name: "Навчальний щит",
      description: "",
      damage: 0,
      defense: 9,
      price: 165,
      image: shield01a.src,
    },
    {
      item_id: 100013,
      type: "shield",
      rarity: 'rare',
      name: "Навчальний щит",
      description: "",
      damage: 0,
      defense: 10,
      price: 650, 
      image: shield01a.src,
    },
    {
      item_id: 10002,
      type: "shield",
      rarity: 'common',
      name: "Сталевий щит",
      description: "",
      damage: 0, 
      defense: 12,
      price: 1600,
      image: shield01b.src,
    },
    {
      item_id: 100021,
      type: "shield",
      rarity: 'uncommon',
      name: "Сталевий щит",
      description: "",
      damage: 0, 
      defense: 13,
      price: 7700,
      image: shield01b.src,
    },
    {
      item_id: 100022,
      type: "shield",
      rarity: 'rare',
      name: "Сталевий щит",
      description: "",
      damage: 0, 
      defense: 14,
      price: 19000,
      image: shield01b.src,
    },
  ]; 