import sword01a from "../../app/_assets/item/sword01a.png";
import sword02a from "../../app/_assets/item/sword02a.png";

export const WeaponItems = [
    {
      item_id: 1,
      type: "weapon",
      rarity: 'common',
      name: "Навчальний меч",
      description: "",
      damage: 1,
      defense: 0,
      price: 30,
      image: sword01a.src,
    },
    {
      item_id: 11,
      type: "weapon",
      rarity: 'uncommon',
      name: "Навчальний меч",
      description: "",
      damage: 2,
      defense: 0,
      price: 100,
      image: sword01a.src,
    },
    {
      item_id: 12,
      type: "weapon",
      rarity: 'rare',
      name: "Навчальний меч",
      description: "",
      damage: 3,
      defense: 0,
      price: 600,
      image: sword01a.src,
    },
    {
      item_id: 2,
      type: "weapon",
      rarity: 'common',
      name: "Сталевий меч",
      description: "",
      damage: 6,
      defense: 1,
      price: 1500,
      image: sword02a.src,
    },
    {
      item_id: 21,
      type: "weapon",
      rarity: 'uncommon',
      name: "Сталевий меч",
      description: "",
      damage: 9,
      defense: 1,
      price: 6500,
      image: sword02a.src,
    },
    {
      item_id: 22,
      type: "weapon",
      rarity: 'rare',
      name: "Сталевий меч",
      description: "",
      damage: 12,
      defense: 1,
      price: 15000,
      image: sword02a.src,
    },
  ];